services:
# front end service
  frontend:
    build: ./client
    ports:
      - "1999:1999"

# database instance
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: walee
      MYSQL_DATABASE: walee
