name: Merge Develop into Main

on:
  push:
    branches:
      - develop

jobs:
  merge_into_main:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Merge develop into main
      run: |
        git fetch origin
        git checkout main
        git merge origin/develop --no-edit
        git push origin main
